const { chromium } = require('D:/pwcli/node_modules/playwright');
const BRAVE = 'C:\\Users\\drbea\\AppData\\Local\\BraveSoftware\\Brave-Browser\\Application\\brave.exe';
const OUT = 'D:\\ToolTip AI\\_qa_dossier\\web-v2';
(async () => {
  const fs = require('fs');
  fs.mkdirSync(OUT, { recursive: true });
  const browser = await chromium.launch({ executablePath: BRAVE, headless: true, args: ['--disable-blink-features=AutomationControlled'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
  page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE', m.text()); });
  await page.goto('file:///D:/ToolTip AI/index.html', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(1800);
  await page.screenshot({ path: OUT + '/hero.png' });
  await page.mouse.move(720, 420);
  await page.waitForTimeout(400);
  await page.screenshot({ path: OUT + '/hero-mouse.png' });
  await page.evaluate(() => window.scrollTo(0, document.querySelector('#demo').offsetTop - 40));
  await page.waitForTimeout(600);
  await page.screenshot({ path: OUT + '/demo.png' });
  await page.evaluate(() => window.scrollTo(0, document.querySelector('#modulos').offsetTop - 40));
  await page.waitForTimeout(600);
  await page.screenshot({ path: OUT + '/mods.png' });
  await page.evaluate(() => window.scrollTo(0, document.querySelector('#precios').offsetTop - 40));
  await page.waitForTimeout(600);
  await page.screenshot({ path: OUT + '/prices.png' });
  await page.click('[data-buy="bundle"]');
  await page.waitForTimeout(500);
  await page.screenshot({ path: OUT + '/checkout.png' });
  console.log('OK shots');
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
